### ISSUE TITLE
Compiling with DuckDB returns postgres_scanner_extension.hpp file not found

### ISSUE THREAD

**Issue by hazelgurule** [duckdb/postgres_scanner#105]
### What happens?

When running `make` in duckdb with 

```
duckdb_extension_load(postgres_scanner
    GIT_URL https://github.com/duckdblabs/postgres_scanner
    GIT_TAG 828578442d18fb3acb53b08f4f54a0683217a2c8
)
```
I get an error like 
```
<path>/duckdb/build/release/codegen/include/generated_extension_headers.hpp:4:10: fatal error: 'postgres_scanner_extension.hpp' file not found
#include "postgres_scanner_extension.hpp"
```

### To Reproduce

In duckdb, create file `extension/extension_config_local.cmake` with the contents 
```
duckdb_extension_load(postgres_scanner
    GIT_URL https://github.com/duckdblabs/postgres_scanner
    GIT_TAG 828578442d18fb3acb53b08f4f54a0683217a2c8
)
```

Then, running `make` will result in the error. 

### OS:

iOS

### PostgreSQL Version:

14.9

### DuckDB Version:

0.8.1

### DuckDB Client:

--

### Full Name:

Hazel Gurule

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I've tried adding this to `extension_config.cmake`:

```cpp
duckdb_extension_load(postgres_scanner
    DONT_LINK
    GIT_URL https://github.com/duckdblabs/postgres_scanner
    GIT_TAG 7bf89ccbc4bd3832418c205522a02a32cc2ae755
)
```

And the compilation seems to work correctly for me. Could you verify that this is still a problem in the latest version?

**Comment by hazelgurule** [comment]
Agreed, it seems to be working now! Will close this out.
