### ISSUE TITLE
SQL syntax NOT

### ISSUE THREAD

**Issue by thomascoquet** [duckdb/postgres_scanner#109]
### What happens?

I have a SQL query with filter_pushdown set to true:

```
SELECT * 
FROM products
WHERE NOT deleted AND sensing_time > '2023-09-01' ;
```

The following SQL is emitted to PostgreSQL:

```sql
COPY (
	SELECT "id", "deleted", "product_id", ...
	FROM products"
	WHERE ctid BETWEEN '(3000,0)'::tid AND '(4000,0)'::tid  
	AND ("sensing_time" > '2023-09-01 00:00:00' AND "sensing_time" IS NOT NULL)
) TO STDOUT (FORMAT binary);
```

No trace of the deleted condition.

---

If the query is:
```
SELECT * 
FROM products
WHERE deleted = FALSE AND sensing_time > '2023-09-01' ;
```
this works as expected.

### To Reproduce

1. Create a table in PostgreSQL:

```sql
CREATE TABLE products (
	id SERIAL,
	deleted BOOL NOT NULL DEFAULT FALSE,
	product_id TEXT NOT NULL,
	sensing_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	CONSTRAINT products_pk PRIMARY KEY (id),
	CONSTRAINT products_uq UNIQUE (product_id)
);
```

2. Execute the query outlined above.

4. Checked using:

```sql
SELECT pid, state, age(clock_timestamp(), query_start), usename, query from pg_stat_activity where query != '<IDLE>' and query not like '%pg_stat_activity%' and state='active' ORDER BY query_start desc;
```

---

I am sorry, I do not know how to print DuckDB SQL statements emitted towards PostgreSQL directly.

### OS:

Ubuntu

### PostgreSQL Version:

12

### DuckDB Version:

v0.9.1-dev43

### DuckDB Client:

python

### Full Name:

Thomas

### Affiliation:

COQUET

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! This is currently intended behavior - only certain filters can be pushed down into Postgres (and table scans in general). Currently this is limited to equality comparisons. We could rewrite `NOT` into an equality with false but this is an issue in upstream DuckDB, not this extension specifically.
