### ISSUE TITLE
Is it possible to speed up copying from Postgres to DuckDB?

### ISSUE THREAD

**Issue by gpointnerbbooe** [duckdb/postgres_scanner#118]
### What happens?

This might be the wrong place to ask this question, but any help on this topic is greatly appreciated. We have built out our DWH using PostgreSQL/PostGIS. A very elegant and easy way to improve the performance of OLAP queries for our BI tool (it already supports DuckDB) would be to copy tables from Postgres to DuckDB using the postgres_scanner extension and then use them for queries from the BI tool. In most cases, copying a table from PG to DuckDB is really fast. (e.g. copying a 1.5 GB dimension table with 31 cols and 1.6 million rows takes around 25 seconds). But for the largest fact table (39 GB, 20 cols, 42 million rows) the time it takes to copy it increases up to one and a half hour. That is probably still excellent for what is happening under hood. However, for our use case, this is too long. So my question is: Can you think of any way to speed up copying these tables or any faster workarounds? I tried to fiddle with the memory and thread configs, but could not get any improvements. Our machine has 8 vcores and 32 GB memory. I am not sure if this is relevant, but very little memory is consumed during copying (~1 GB). Any hints are greatly valued.

### To Reproduce

I attached the tables using postgres_attach (tried with and without pushdown, I also tried the postgres_scan function).
Then I copied the tables using Python like this (I also tried with the CLI):
![image](https://github.com/duckdb/postgres_scanner/assets/102801472/51406ade-af8b-4b7c-aec3-18051f25a5d0)

### OS:

Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-164-generic x86_64)

### PostgreSQL Version:

12.16

### DuckDB Version:

0.9.2-dev96

### DuckDB Client:

Python, CLI

### Full Name:

Georg Pointner

### Affiliation:

BBOÖ Breitband Oberösterreich GmbH

### Have you tried this on the latest `main` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
The data transfer is done internally by performing a binary copy over a `psql` connection. Likely most of the time is spend on transferring the (uncompressed) data over the socket. Perhaps a fix would be to run DuckDB on the same machine where Postgres is running and read the data from there?

**Comment by Mytherin** [comment]
Could you perhaps try setting `SET preserve_insertion_order=false;` before doing the import and checking if that speeds things up?

**Comment by markhalonen** [comment]
> Could you perhaps try setting SET preserve_insertion_order=false; before doing the import and checking if that speeds things up?

I'm working on a similar issue and this results in a 4X speedup without foreign keys, nice! For a table with 350k rows and 3 foreign key columns, export time jumps from 1.3 seconds to 33 seconds. Any tips on faster inserts to a table with foreign keys?

**Comment by gpointnerbbooe** [comment]
> Could you perhaps try setting `SET preserve_insertion_order=false;` before doing the import and checking if that speeds things up?

Thank you! For the 1.5 GB table the duration drops from 25 secs to 10 secs. For the 39 GB table the duration drops from 1h 30 mins to 45 mins.

**Comment by Mytherin** [comment]
> > Could you perhaps try setting `SET preserve_insertion_order=false;` before doing the import and checking if that speeds things up?
> 
> Thank you! For the 1.5 GB table the duration drops from 25 secs to 10 secs. For the 39 GB table the duration drops from 1h 30 mins to 45 mins.

To further increase performance you could try increasing the number of threads (e.g. `SET threads=16`).
