### ISSUE TITLE
Inquiry - Licensing question

### ISSUE THREAD

**Issue by chrisfw** [duckdb/postgres_scanner#133]
### What happens?

Hello, 

I just noticed that the postgres_scanner and mysql_scanner extensions are both GPL and the postgres_scanner landing page mentions other licensing options.  I was surprised that they are not MIT licensed, but wondering what other license these extensions are available under?

Regards,
Chris Whelan 

### To Reproduce

Not a bug

### OS:

Windows

### PostgreSQL Version:

14.5

### DuckDB Version:

0.9.2

### DuckDB Client:

cli

### Full Name:

Chris Whelan

### Affiliation:

Systems and Software

### Have you tried this on the latest `main` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by szarnyasg** [comment]
Hi @chrisfw, I'm happy to discuss this via email. Can you please drop a line to gabor@duckdblabs.com? Gabor
