### ISSUE TITLE
Cannot retrieve big table from postgres

### ISSUE THREAD

**Issue by hengaini2055** [duckdb/postgres_scanner#149]
I use the following statement attach a postgres database
```
ATTACH 'dbname=postgres host=127.0.0.1 port=5432 user=postgres password=1122334455' as pg_duckdb (type postgres);
```
I can retrieve a little table such as 
```
select * from pg_duckdb.t1
```
But when I retrieve a big table (1,000,000), get the errors:
```
select * from pg_duckdb.t_random
------
SQL ERROR: Invalid Error: Failed to prepare COPY "
	COPY (SELECT "generate_series" FROM "public"."t_random" WHERE ctid BETWEEN '(0,0)'::tid AND '(1000,0)'::tid) TO STDOUT (FORMAT binary);
	": 
------
```
I execute this statement from DBeaver 23.3.

OS: windows 11
DBeaver: 23.3.0
duckdb: 0.9.2
Postgres: 15.4

**Comment by Mytherin** [comment]
Thanks for the report! This is an issue specific to certain clients (in this case the JDBC client). I've pushed a fix in #150. As a work-around you could run `SET pg_connection_limit=1`.

**Comment by hengaini2055** [comment]
Thank you! The other errors come:



&nbsp;


张军峰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月14日(星期四) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [duckdb/postgres_scanner] Cannot retrieve big table from postgres (Issue #149)





 
Thanks for the report! This is an issue specific to certain clients (in this case the JDBC client). I've pushed a fix in #150. As a work-around you could run SET pg_connection_limit=1.

**Comment by hengaini2055** [comment]
![image](https://github.com/duckdb/postgres_scanner/assets/20587475/a61bb704-b5fa-4e58-928e-be6674f7956c)
In command ,there are different errors.
Does I update the extensions to the newest version?

**Comment by Mytherin** [comment]
You can install the nightly as follows:

```sql
force install postgres_scanner from 'http://nightly-extensions.duckdb.org';
```
