### ISSUE TITLE
wrong when query greenplum tables

### ISSUE THREAD

**Issue by wonb168** [duckdb/postgres_scanner#152]
### What happens?

I attached a greenplum db as gp,
and I can query data by postgre_query(),
but can't query by gp.table

and then how to write data into greenplum table 

### To Reproduce

```
select * from postgres_query('uat','select * from tenant_snowbeer_dm.dim_sku limit 2')--ok
select * from uat.tenant_snowbeer_dm.dim_sku--wrong：ava.sql.SQLException: Catalog Error: Table with name dim_sku does not exist!
```

### OS:

mac14

### PostgreSQL Version:

6.12.1(gp,pg:9.4)

### DuckDB Version:

0.9.2

### DuckDB Client:

python

### Full Name:

wonb168

### Affiliation:

Linezone

### Have you tried this on the latest `main` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for reporting - could you check if this issue is still present on the latest version of the postgres extension?
