### ISSUE TITLE
Can't build locally

### ISSUE THREAD

**Issue by ila** [duckdb/postgres_scanner#161]
Hi, I am trying to build the postgres_scanner locally since I need to develop my code using it. However, I can't manage to make it work (I used the pre-build one from your archives so far, but it is not enough for my use case). The steps I did are:
- cloned the repo in the extension folder
- tried adding the postgres_scanner to BUILD_EXTENSIONS, gave me an error that the postgres_scanner header is not found
- tried building it as standalone library with make, doesn't find the duckdb library

Could you give me the steps to build it locally and load it in DuckDB? I am using 0.9.2. Thanks!

**Comment by Mytherin** [comment]
Does running [make](https://github.com/duckdb/postgres_scanner#building--loading-the-extension) not work for you?

**Comment by ila** [comment]
Nope, gives me an error that it can't find the duckdb/build folder (at the top of my mind, don't have my laptop atm sorry). Is my procedure correct though? Do I need to disable anything in the extension loading settings? Is there any way to do this with cmake?Op 10 jan 2024 om 18:35 heeft Mark ***@***.***> het volgende geschreven:﻿
Does running make not work for you?

**Comment by Mytherin** [comment]
Likely you haven't pulled the submodules in:

```bash
git submodule init
git pull --recurse-submodules
```

I've added it to the README now

**Comment by ila** [comment]
This works with make, but cmake still gives me an error: 
```
CMake Error at CMakeLists.txt:129 (build_loadable_extension):
  Unknown CMake command "build_loadable_extension".
```

**Comment by Mytherin** [comment]
You're most likely calling cmake incorrectly - `make` only calls `cmake`. Have a look at the makefile to check the parameters that are used.
