### ISSUE TITLE
Support views in postgres_attach procedure

### ISSUE THREAD

**Issue by jacques-charnay** [duckdb/postgres_scanner#179]
Currently, the `postgres_attach` procedure allows to conveniently create DuckDB views for all **tables** in a given PostgreSQL schema. (with for example a syntax like `CALL postgres_attach('', source_schema='analysis', sink_schema='main')`).
It would also be practical to automatically create DuckDB views for PostgreSQL **views** in the source schema. In order not to change the current behavior, taking views into account could be an optional parameter.

**Comment by Mytherin** [comment]
Thanks for the suggestion, however, `postgres_attach` is deprecated. I would suggest switching over the new [ATTACH syntax](https://github.com/duckdb/postgres_scanner?tab=readme-ov-file#reading-data-from-postgres) which supports querying from Postgres views already.
