### ISSUE TITLE
Mention parallel scan is efficient only since Postgres 14

### ISSUE THREAD

**Issue by anayrat** [duckdb/postgres_scanner#186]
### What happens?

Before Postgres 14, range filtering on _ctid_ column implies a seqscan.

### To Reproduce

Perform parallel scan on pg before Postgres 14.

Your optimization thanks to range filtering on *ctid* column is efficient only since Postgres 14 thanks to this commit : https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=bb437f995d47405ecd92cf66df71f7f7e40ed460

https://www.postgresql.org/docs/14/release-14.html
> Allow efficient heap scanning of a range of [TIDs](https://www.postgresql.org/docs/14/datatype-oid.html#DATATYPE-OID-TABLE) (Edmund Horner, David Rowley)
> Previously a sequential scan was required for non-equality TID specifications.

Maybe, you should disable it on Postgres < 14 ?

### OS:

Linux

### PostgreSQL Version:

14

### DuckDB Version:

any

### DuckDB Client:

any

### Full Name:

Adrien Nayrat

### Affiliation:

Self Employed

### Have you tried this on the latest `main` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for reporting! I have tested this and can confirm that the parallel ctid scan does not work very well in older versions. I have disabled them now in versions < 14 in https://github.com/duckdb/postgres_scanner/pull/195.
