### ISSUE TITLE
CREATE SCHEMA IF NOT EXISTS | Mis-translated?

### ISSUE THREAD

**Issue by tmontes** [duckdb/postgres_scanner#198]
### What happens?

* `CREATE SCHEMA IF NOT EXISTS ...` on an attached PostgreSQL DB seems to be translated to `CREATE SCHEMA ...`.
* The `IF NOT EXISTS` "segment" is not respected.

### To Reproduce

SETUP:

* Set the PostgreSQL libpq env vars to successfully connect to a DB.
* Ensure permissions to `CREATE SCHEMA` on that DB are given.
* Ensure that DB is empty.
 
SQL SCRIPT:
```
ATTACH '' AS psql (TYPE postgres);

CREATE SCHEMA IF NOT EXISTS psql.s;
```

RESULT:
* Works on the first run, when the `s` schema is non-existent on the PostgreSQL DB.
* Fails on the second because it attempts to create the already-present `s` schema on the PostgreSQL DB.

OBSERVATION:
* Interestingly, a `CREATE TABLE IF NOT EXISTS` seems to be respected.

CLI SESSION:
```
$ duckdb < ups.sql
Invalid Error: Failed to execute query "BEGIN TRANSACTION;
CREATE SCHEMA "s"": ERROR:  schema "s" already exists
$
```

### OS:

macOS (likely irrelevant)

### PostgreSQL Version:

13 (likely irrelevant)

### DuckDB Version:

v0.10.1 4a89d97db8

### DuckDB Client:

macOS CLI

### Full Name:

Tiago Montes

### Affiliation:

Freelance Consultant

### Have you tried this on the latest `main` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by tmontes** [comment]
(heads-up: my C++ skills are severely outdated, last time I worked with it was nearly 20 years ago!!! yeah, early days!)

FURTHER DIAGNOSTIC:

* The relevant code seems to be [`PostgresSchemaSet::CreateSchema`](https://github.com/duckdb/postgres_scanner/blob/656ab0b265f8cba874e30a154fc13c368862067a/src/storage/postgres_schema_set.cpp#L76C28-L76C59).
* A hard-coded `CREATE SCHEMA` is used.
* Seems to disregard the `CreateSchemaInfo`'s `on_conflict` member.

WHERE I LEARNED THIS:
(Digged through `duckdb`'s code and found)
* [`CreateSchemaInfo`](https://github.com/duckdb/duckdb/blob/5f74399a0e7a93609546ecc86b2ae9285dffcb7d/src/include/duckdb/parser/parsed_data/create_schema_info.hpp#L15) with its [`on_conflict` member](https://github.com/duckdb/duckdb/blob/5f74399a0e7a93609546ecc86b2ae9285dffcb7d/src/include/duckdb/parser/parsed_data/create_info.hpp#L39C19-L39C30)...
* ...that seems to be used [here](https://github.com/duckdb/duckdb/blob/5f74399a0e7a93609546ecc86b2ae9285dffcb7d/src/include/duckdb/parser/parsed_data/create_schema_info.hpp#L29) to adequately generate the correct `CREATE SCHEMA` statements (within DuckDB, I suppose!).

**Comment by tmontes** [comment]
MY FEEL:

* Adapting the same `on_conflict`-based `CREATE SCHEMA` generation code on this extension should be easy to accommodate -- from the inspiration in DuckDB's code.

MY (failed) ATTEMPT:
(not that I feel very confident in submitting a PR for this!)

* Tried building from source:
  * Builds ok.
  * Runtime failure when connecting to PostgreSQL.
* Using macOS 12.7.4 + Xcode tools + brew-installed CMake.
* Cloned this repo + followed guidance in the `README`.
* I get a (very) interesting failure in connecting to PostgreSQL:
```
$ ./build/release/duckdb -unsigned
v0.10.1 4a89d97db8
Enter ".help" for usage hints.
D LOAD 'build/release/extension/postgres_scanner/postgres_scanner.duckdb_extension';
D ATTACH '' AS psql (TYPE postgres);
IO Error: Unable to connect to Postgres at : connection to server at "psql.lan.tmont.es" (192.168.111.25), port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet
connection to server at "psql.lan.tmont.es" (192.168.111.25), port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet
```

(same shell, brew installed CLI)
```
tiago.montes (~/Temp/x-ddb-psql/postgres_scanner): duckdb
v0.10.1 4a89d97db8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH '' AS psql (TYPE postgres);
D .exit
```

THOUGHTS:
* Something must be wrong in my build process...
* ...but I could not figure out what, after having strictly followed the README.


PARTING WORDS:
* Thanks for acknowledging (or not!) that this is a bug.
* Happy to contribute with a fix PR, but I will need hand holding...
* ...happy to review PRs once I get my build process working.


All in all, thanks for a wonderful project!
Cheers

**Comment by Mytherin** [comment]
Thanks for the report! I have a fix open at https://github.com/duckdb/postgres_scanner/pull/199

**Comment by tmontes** [comment]
Wow, thanks for the quick response!... :-)

In wanting to try your proposed change, I built it locally with:

```
$ git clone git@github.com:Mytherin/postgres_scanner.git
$ cd postgres_scanner
$ git checkout -b createschemaifnotexists origin/createschemaifnotexists
$ git submodule init    
$ git pull --recurse-submodules                                          
$ make
...
$ echo $?
0
```

Running it fails on attach with a "no PostgreSQL user name specified in startup packet" error message:
```
$ ./build/release/duckdb -unsigned
v0.10.1 4a89d97db8
Enter ".help" for usage hints.
D LOAD 'build/release/extension/postgres_scanner/postgres_scanner.duckdb_extension';
D ATTACH '' AS psql (TYPE postgres);
IO Error: Unable to connect to Postgres at : connection to server at "psql.lan.tmont.es" (192.168.111.25), port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet
connection to server at "psql.lan.tmont.es" (192.168.111.25), port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet

D .exit
$
```

This is no different from what I experienced yesterday -- running the brew-installed version works:

```
$ duckdb
v0.10.1 4a89d97db8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH '' AS psql (TYPE postgres);
D .exit
$
```


I understand this is a different topic -- but could you share any hint as to how I can diagnose my non-working builds?

Again, thanks a lot.

**Comment by Mytherin** [comment]
I'm not sure what's going wrong there. Maybe just try the nightly build in a few hours when CI finishes building it:

```sql
INSTALL postgres FROM 'http://nightly-extensions.duckdb.org';
```

**Comment by tmontes** [comment]
> I'm not sure what's going wrong there. Maybe just try the nightly build in a few hours when CI finishes building it:

Thanks, I'll do just that!
