### ISSUE TITLE
Parallel Scans not partitioning?

### ISSUE THREAD

**Issue by m1hawkgsm** [duckdb/postgres_scanner#20]
I have two (related) questions around `postgres_scan` and `postgres_scan_pushdown`.   I am testing these functions to fetch data from a Postgres read replica. I'm finding that the "parallelization" and TID scan stuff doesn't seem to work as advertised in the blog, but maybe I'm just not understanding how it works.

Consider the following example query:
```
select prediction_log_id from rep.tbl where created_at between '2022-09-30'::timestamp and '2022-10-01'::timestamp
```
(maybe irrelevant, but there is an index on `created_at`).

Now, I ran this in DuckDB using both functions to see how the extension works with/without predicate pushdown and I checked on the PG instance using:

```
SELECT pid, state, age(clock_timestamp(), query_start), usename, query from pg_stat_activity where query != '<IDLE>' and query not like '%pg_stat_activity%' and state='active' ORDER BY query_start desc;
```

With `postgres_scan_pushdown`, I get something like this:
```
COPY (SELECT "prediction_log_id" FROM "rep"."tbl" WHERE ctid BETWEEN '(13582000,0)'::tid AND '(13583000,0)'::tid AND ("created_at" >= '2022-09-30 00:00:00' AND "created_at" <= '2022-10-01 00:00:00' AND "created_at" IS NOT NULL)) TO STDOUT (FORMAT binary);
```

Frequently refreshing, the `ctid` range indeed increments by `1000` as the blog post indicates, but there isn't any parallel queries run, it's just 1 process.  Is that intentional?

With `postgres_scan`, I get something like this:
```
COPY (SELECT "prediction_log_id" FROM "rep"."tbl" WHERE ctid BETWEEN '(0,0)'::tid AND '(1000,0)'::tid ) TO STDOUT (FORMAT binary);
```

But this time I get _three_ of these queries at a time, but they don't have different `ctid` ranges as I expected (like, literally the same exact query, three times).  So in this case, looks like there's parallelization, but you don't have separate ranges going on at once. Waiting a while and refreshing, I'd find a fresh new set of three queries with updated `ctid` ranges but all the same (eg. all updated from 0-1000 to 1000-2000).  Is that intentional?

Also interesting tidbit: after testing with different tables and queries, I find that the `postgres_scan_pushdown` function never starts with a `0-1000` CTID range, but somewhere in the middle. Does this mean the pushdown function is smarter with reading TIDs?

I am using DuckDB version 0.5.1, reading from PostgreSQL 10.18

**Comment by hannes** [comment]
Can you try with the latest version of postgres_scanner? We fixed some bugs related to this.

**Comment by sspaeti** [comment]
I just ran into the same when querying a view. Stupid question: How would you install the latest version? Would I need to build it myself from the source, or can I do some UNINSTALL cmd?

I did:
```sh
duckdb
INSTALL postgres_scanner;
LOAD postgres_scanner;
```

**Comment by hannes** [comment]
Ah yes, views are not yet supported.

**Comment by Mytherin** [comment]
Thanks for the report! This most likely has already been fixed, e.g. the following queries in DuckDB:
```sql
ATTACH 'dbname=postgresscanner' AS postgres (TYPE POSTGRES);
SET pg_debug_show_queries=true;
SELECT SUM(l_orderkey) FROM postgres.lineitem;
```

Result in the following Postgres queries:

```sql
COPY (SELECT "l_orderkey" FROM "public"."lineitem" WHERE ctid BETWEEN '(0,0)'::tid AND '(1000,0)'::tid) TO STDOUT (FORMAT binary);
COPY (SELECT "l_orderkey" FROM "public"."lineitem" WHERE ctid BETWEEN '(1000,0)'::tid AND '(2000,0)'::tid) TO STDOUT (FORMAT binary);
COPY (SELECT "l_orderkey" FROM "public"."lineitem" WHERE ctid BETWEEN '(2000,0)'::tid AND '(3000,0)'::tid) TO STDOUT (FORMAT binary);
COPY (SELECT "l_orderkey" FROM "public"."lineitem" WHERE ctid BETWEEN '(3000,0)'::tid AND '(4000,0)'::tid) TO STDOUT (FORMAT binary);
COPY (SELECT "l_orderkey" FROM "public"."lineitem" WHERE ctid BETWEEN '(4000,0)'::tid AND '(5000,0)'::tid) TO STDOUT (FORMAT binary);
```

Feel free to re-open if the issue persists.
