### ISSUE TITLE
Support encoding to a file

### ISSUE THREAD

**Issue by adriangb** [duckdb/postgres_scanner#204]
Copying over from https://github.com/duckdb/duckdb/discussions/11438

DuckDB has become an amazing in memory ETL/data pipeline tool. It can read and write to almost anything. Would it be possible to add an option to copy to any DuckDB source to a binary postgres dump *file*? The equivalent of copying a parquet file (for example) to a postgres table then doing `\copy mytable TO 'data.bin' WITH (FORMAT BINARY)` via psql.

One option for an API would be something like `COPY mytable TO STDOUT WITH (FORMAT POSTGRES_BINARY)` / `COPY 'file.parquet' TO 'data.bin' WITH (FORMAT POSTGRES_BINARY)`. I'm hoping this is not a difficult request since it's in some ways a subset of the functionality alraedy implemented.

As an example use case I made a library for this that DuckDB could then replace and it has 200+ stars, which is more than this repo currently has (not that it's a fair comparison, just pointing out that it's a real use case): https://github.com/adriangb/pgpq

**Comment by Mytherin** [comment]
Thanks - that's an interesting idea. I've opened a PR that implements this in https://github.com/duckdb/postgres_scanner/pull/205. Indeed it can utilize existing logic. Perhaps give it a spin and see if it works as you expect it to?

**Comment by adriangb** [comment]
Just to complete the loop, once the next release is made this will be possible:

```python
import duckdb
from fsspec import filesystem

fs = filesystem('memory')
duckdb.register_filesystem(fs)
duckdb.sql("LOAD postgres;'")
duckdb.sql("COPY (SELECT 1 AS a, 2 AS b) TO 'memory://test.bin' (FORMAT postgres_binary)")
print(fs.open('test.bin').read())  # b'PGCOPY\n\xff\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\x02\xff\xff'
```
