### ISSUE TITLE
Add support for managing Postgres credentials through the secret manager

### ISSUE THREAD

**Issue by Mytherin** [duckdb/postgres_scanner#213]
DuckDB now includes a secret manager that can be used to manage secrets - we should add support for managing Postgres' databases through this mechanism as well.

**Comment by LMnet** [comment]
Small addition - not only for postgres, but for any `attach`. There is also mysql.

**Comment by Mytherin** [comment]
And now in MySQL in https://github.com/duckdb/duckdb_mysql/pull/64
