### ISSUE TITLE
Suggestion: Add application_name setting for PG connection

### ISSUE THREAD

**Issue by beeing** [duckdb/postgres_scanner#224]
This allow us to have better management on the duckdb connections to PG.

Thanks in advance.

**Comment by Mytherin** [comment]
Does the application_name parameter not work for you? See the connection options here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS

**Comment by beeing** [comment]
Yes, it does. I don't see this in the docs or source. Does this extension pass this parameter to PG?

If yes, then it should be good enough. Thanks!

**Comment by Mytherin** [comment]
Not all options are listed in the docs:

> The ATTACH command takes as input a [libpq connection string](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) - which is a set of key=value pairs separated by spaces. Below are some example connection strings and commonly used parameters. A full list of available parameters can be found [in the Postgres documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS).

**Comment by beeing** [comment]
That should be it, thanks for the help.
