### ISSUE TITLE
syntax error at or near "FORMAT"

### ISSUE THREAD

**Issue by yulk** [duckdb/postgres_scanner#241]
### What happens?

src/postgres_scanner.cpp

	lstate.sql = StringUtil::Format(
		    R"(
	COPY (SELECT %s FROM %s.%s %s) TO STDOUT (FORMAT binary);
	)",

in postgresql 9.2 need to write as:

COPY "tablename" TO STDOUT WITH (FORMAT "binary")

you should quote it.

https://www.postgresql.org/message-id/1309878337-sup-685%40alvh.no-ip.org

### To Reproduce

COPY "tablename" TO STDOUT WITH (FORMAT "binary")

### OS:

windows

### PostgreSQL Version:

9.2

### DuckDB Version:

1.0

### DuckDB Client:

client

### Full Name:

dreamrise

### Affiliation:

None

### Have you tried this on the latest `main` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I've pushed a fix in https://github.com/duckdb/postgres_scanner/pull/257
