### ISSUE TITLE
Schema name is not necessary in SQL query if attach has specified a schema name.

### ISSUE THREAD

**Issue by robotslacker** [duckdb/postgres_scanner#265]
### What happens?

With this commit https://github.com/duckdb/postgres_scanner/commit/33598a6e91c95497cd92c78bb888bbcfdcf0cae8 , we now can attach to a specific schema instead of the entire target database, which helps us a lot. thanks a lot.

But since the schema parameter is supported, it becomes meaningless to require the schema name in query sel when accessing data.

```
attach "" as s (TYPE POSTGRES, SCHEMA schema1).
```

The expected behavior : select * from s.tab1;
Current behavior:  select * from s.schema1.tab1;

### To Reproduce

```
attach "" as s (TYPE POSTGRES, SCHEMA schema1).
```

### OS:

Linux CentOS8

### PostgreSQL Version:

15

### DuckDB Version:

1.1.0

### DuckDB Client:

jdbc

### Full Name:

Shi.Zhao

### Affiliation:

Oracle

### Have you tried this on the latest `main` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

The schema is already set as the default schema, so what you are suggesting is already the case, e.g.:

```sql
attach '' as s (type postgres);
select * from s.t;
-- Catalog Error: Table with name t does not exist!
-- Did you mean "s.s1.t"?
-- LINE 1: select * from s.t;
--                       ^
select * from s.s1.t;
┌───────┐
│   c   │
│ int32 │
├───────┤
│    42 │
└───────┘
detach s;
attach '' as s (type postgres, schema s1);
D select * from s.t;
┌───────┐
│   c   │
│ int32 │
├───────┤
│    42 │
└───────┘
```

Or am I missing something here?

**Comment by robotslacker** [comment]
I tried it again and it seems to be just as you said.
I am confused and I don't understand what is going on.

Anyway, I should close this case first.
I am very sorry for the trouble.
