### ISSUE TITLE
load postgres_scanner in R Windows crash R

### ISSUE THREAD

**Issue by j4david** [duckdb/postgres_scanner#33]
Hello.

I tried to use the DuckDB postgres_scanner extension on R and RStudio for Windows (x86_64) and it crashed when I do the "LOAD postgres_scanner;".  "R Session Aborted" message. I tried both the binary version of DuckDB (0.5.1) and the source version, built and installed with install.packages("duckdb", type = "source"). Both methods failed.

On Linux, Debian bookworm, same machine, it worked correctly. Built the DuckDB R package from source in RStudio.

I used ok this extension with CLI client and DBeaver in Windows and Linux.

Thanks very much for your work. Duckdb is becoming one of my favorite library for data work.

**Comment by Alex-Monahan** [comment]
Hmm, one small attempt, then this is out of my league!
Could you try wrapping postgres_scanner in single quotes in your load statement?
It still shouldn't crash as is though!

**Comment by j4david** [comment]
Same behavior. Crashed R 
dbExecute(con,"LOAD 'postgres_scanner';")
and 
dbExecute(con,"LOAD postgres_scanner;")

**Comment by jllipatz** [comment]
Same thing for me.
I opened https://github.com/duckdb/duckdb/discussions/4980.

In th hope that I could help.

**Comment by Mytherin** [comment]
I think this is likely fixed now - this is an old issue related to extension loading on Windows in R
