### ISSUE TITLE
can't scan partitional son table

### ISSUE THREAD

**Issue by wonb168** [duckdb/postgres_scanner#58]
### What happens?

I use postgres_scan to query patitional son table, like this:

```
create or replace view tenant_qisefang_biz.gto_action_record as SELECT * FROM postgres_scan('postgres://gpadmin:pwd@192.168.0.161:2345/qsf_prod', 'biz', 'rst_ra_skc_org_detail_1_prt_p20221011')
```
Create view all OK, but when query, I tested three db, only One(qsf_prod) is OK, other two are error:
```
IOException: IO Error: Unable to query Postgres: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
 server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

### To Reproduce

I dont't know how to reproduce it,
qsf_test and qsf_prod are same tenant in different environment, have the same DDL about the partition table.
the three table attitudes in pg_class:
<html>
<body>

envirement | relname | relnamespace | reltype | reloftype | relowner | relam | relfilenode | reltablespace | relpages | reltuples | relallvisible | reltoastrelid | relhasindex | relisshared | relpersistence | relkind | relstorage | relnatts | relchecks | relhasoids | relhaspkey | relhasrules | relhastriggers | relhassubclass | relispopulated | relreplident | relfrozenxid | relminmxid | relacl | reloptions
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
qsf-test | rst_ra_skc_org_detail_1_prt_p20221011 | 236645463 | 328576078 | 0 | 236645467 | 0 | 69327401 | 236645454 | 9201 | 39807 | 0 | 353502973 | TRUE | FALSE | p | r | h | 223 | 1 | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | d | 24425733 | 1 | {backend_qisefang_test=arwdDxt/etl_qisefang_test,etl_qisefang_test=arwdDxt/etl_qisefang_test,model_qisefang_test=arwdDxt/etl_qisefang_test,query_qisefang_test=arwdDxt/etl_qisefang_test,etl_qisefang_test_readonly=arwdDxt/etl_qisefang_test,linezone_t2_readonly=r/etl_qisefang_test} | NULL
qsf-prod | rst_ra_skc_org_detail_1_prt_p20221011 | 176052483 | 210101537 | 0 | 173967062 | 0 | 42205523 | 173967034 | 7621 | 12997 | 0 | 210101542 | TRUE | FALSE | p | r | h | 223 | 1 | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | d | 14160586 | 1 | {etl_qisefang_prod=arwdDxt/etl_qisefang_prod,etl_qisefang_prod_readonly=arwdDxt/etl_qisefang_prod,backend_qisefang_prod=arwdDxt/etl_qisefang_prod,model_qisefang_prod=arwdDxt/etl_qisefang_prod,query_qisefang_prod=arwdDxt/etl_qisefang_prod,linezone_t2_readonly=r/etl_qisefang_prod} | NULL
yg-prod | rst_ra_skc_org_detail_1_prt_p20221011 | 63377625 | 210493179 | 0 | 26947415 | 0 | 42296994 | 26947402 | 48655 | 542035 | 0 | 210493183 | TRUE | FALSE | p | r | c | 223 | 1 | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | d | 0 | 0 | {backend_yuege_prod=arwdDxt/etl_yuege_prod,etl_yuege_prod=arwdDxt/etl_yuege_prod,model_yuege_prod=arwdDxt/etl_yuege_prod,query_yuege_prod=arwdDxt/etl_yuege_prod,etl_yuege_prod_readonly=arwdDxt/etl_yuege_prod,linezone_t2_readonly=r/etl_yuege_prod} | {appendonly=true,orientation=column,compresstype=zlib,compresslevel=5}

</body>
</html>

### OS:

centos7

### PostgreSQL Version:

9.4（greenplum6.12）

### DuckDB Version:

0.6.0

### DuckDB Client:

Python

### Full Name:

Changzhen Wang

### Affiliation:

linezonedata

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by wonb168** [comment]
I checked the pg_log, found error because of the copy sql with the wrong ctid.
```
COPY (SELECT NULL FROM tenant_yuege_biz.rst_ra_skc_org_detail_1_prt_p20221123 WHERE ctid BETWEEN '(0,0)'::tid AND '(4294967295,0)'::tid ) TO STDOUT (FORMAT binary);
```
```
but the ctid is WRONG :
```
COPY (SELECT NULL FROM tenant_yuege_biz.rst_ra_skc_org_detail_1_prt_p20221123 WHERE ctid BETWEEN '(0,0)'::tid AND '(1000,0)'::tid ) TO STDOUT (FORMAT binary);

SELECT min(ctid),max(ctid) FROM tenant_yuege_biz.rst_ra_skc_org_detail_1_prt_p20221123--(33554432,2)	(33554435,17469)
SELECT NULL FROM tenant_yuege_biz.rst_ra_skc_org_detail_1_prt_p20221123 WHERE ctid BETWEEN '(33554432,2)'::tid AND '(33554432,1000)'::tid
```
but use the min and max ctid, alse error:
```
COPY (SELECT NULL FROM ""tenant_yuege_biz"".""rst_ra_skc_org_detail_1_prt_p20221123"" WHERE ctid BETWEEN '(0,0)'::tid AND '(4294967295,0)'::tid ) TO STDOUT (FORMAT binary);
",0,,"postgres.c",1639,
2022-11-23 20:40:43.313946 CST,,,p23011,th0,,,2022-11-23 20:40:42 CST,0,con813,cmd2,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x7fd6fb14a630 libpthread.so.0 <symbol not found> + 0xfb14a630
2    0xf9cc68 postgres <symbol not found> (CXformUtils.cpp:2234)
```
and another DB is OK, 
the OK one:
```
SELECT min(ctid),max(ctid) FROM tenant_qisefang_biz.rst_ra_skc_org_detail_1_prt_p20221123--(11360,7)	(33325,2)
SELECT NULL FROM tenant_qisefang_biz.rst_ra_skc_org_detail_1_prt_p20221123 WHERE ctid BETWEEN '(11360,7)'::tid AND '(33325,2)'::tid

**Comment by Mytherin** [comment]
Thanks for the report! Unfortunately I can't find enough information here to reproduce the issue.
