### ISSUE TITLE
Postgres scanner does not attach partitioned tables

### ISSUE THREAD

**Issue by dpprdan** [duckdb/postgres_scanner#91]
### What happens?

(from https://github.com/duckdb/duckdb/discussions/6934)

After attaching a PostgreSQL DB

```
D CALL postgres_attach('my_connection_string', source_schema='public');
```

I try to query a partitioned table from the Postgres DB and get the following error.

```
D SELECT * FROM partitioned_table LIMIT 10;
Error: Catalog Error: Table with name partitioned_table does not exist!
Did you mean "partitioned_table _0"?
LINE 1: SELECT * FROM partitioned_table LIMIT 10;
```

`PRAGMA show_tables;` indeed does not show the `partioned_table` but (apparently all of) its partitions. 

A query using `postgres_scan()` does succeed however.

```
SELECT * FROM postgres_scan('my_connection_string', 'public', 'partitioned_table') LIMIT 10;

[output from query]
```

### To Reproduce

Create a [partitioned table](https://www.postgresql.org/docs/current/ddl-partitioning.html) in Postgres, then see above.

### OS:

Windows

### PostgreSQL Version:

12.12

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Daniel Possenriede

### Affiliation:

QUIS

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I believe this is fixed in #111 with the new `ATTACH` syntax. The following works for me now:

###### Postgres
```sql
CREATE TABLE measurement (
    city_id         int not null,
    logdate         date not null,
    peaktemp        int,
    unitsales       int
) PARTITION BY RANGE (logdate);
CREATE TABLE measurement_y2006m02 PARTITION OF measurement
    FOR VALUES FROM ('2000-01-01') TO ('2006-03-01');
INSERT INTO measurement VALUES (1, DATE '2000-01-01', 1, 1);
```

###### DuckDB
```sql
ATTACH 'dbname=postgresscanner' AS postgres (TYPE POSTGRES);
SELECT * FROM postgres.measurement;
┌─────────┬────────────┬──────────┬───────────┐
│ city_id │  logdate   │ peaktemp │ unitsales │
│  int32  │    date    │  int32   │   int32   │
├─────────┼────────────┼──────────┼───────────┤
│       1 │ 2000-01-01 │        1 │         1 │
└─────────┴────────────┴──────────┴───────────┘
```
