### ISSUE TITLE
Postgres NUMERIC columns - overflowing values when inserting into duckdb's DECIMAL

### ISSUE THREAD

**Issue by jhrcek** [duckdb/postgres_scanner#92]
### What happens?

When importing data from postgres into duckdb using `postgres_scan` function, numeric values with large magnitude are overflowing in duckdb.

### To Reproduce

1. Start latest version (15.2) of postgresql locally in docker (but it's also reproducible with older postgres, like 12.11)
```bash
$ docker run \
-p 5432:5432 \
-e POSTGRES_USER=test \
-e POSTGRES_PASSWORD=test \
-e POSTGRES_DB=test \
-e PGDATA=/var/lib/postgresql/data/pgdata \
--tmpfs /var/lib/postgresql/data/pgdata \
postgres:15.2-alpine \
-c log_statement=all
```

2. Connect to test db using psql
```bash
psql "host=localhost user=test password=test"
```

Create table with NUMERIC column (from [postgres manual](https://www.postgresql.org/docs/14/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL): "Specifying NUMERIC without any precision or scale creates an “unconstrained numeric” column in which numeric values of any length can be stored, up to the implementation limits.)

```sql
create table test (mycolumn numeric);
```

Insert bunch of values of different magnitudes.

```sql
INSERT INTO test (mycolumn)
VALUES
(0.001),
(0.01),
(0.1),
(1),
(10),
(100),
(1000),
(10000),
(100000),
(1000000),
(10000000),
(100000000),
(1000000000),
(10000000000),
(100000000000),
(1000000000000),
(10000000000000),
(100000000000000),
(1000000000000000),
(10000000000000000),
(100000000000000000),
(1000000000000000000),
(10000000000000000000),
(100000000000000000000);
```

2. Import the data into duckdb.
   When you create column of type `numeric` in duckdb, it is implicitly translated to `decimal(18,3)`.
   To allow numbers up to 100000000000000000000 (1 and 20 zeros, with 3 decimal digits) I use `decimal(24,3)`.
   But this issue is reproducible also when I use the maximum allowed scale (`decimal(38,3)`).
   
```bash
$ duckdb demo.db
v0.7.1 b00b93f0b1
Enter ".help" for usage hints.
D LOAD postgres;
D create table test(mycolumn decimal(24,3));
D insert into test(mycolumn) select * from postgres_scan('host=localhost user=test password=test', 'public', 'test');
```

3. observe that the largest values are not correct:

```
D select * from test;
┌──────────────────────────┐
│         mycolumn         │
│      decimal(24,3)       │
├──────────────────────────┤
│                    0.001 │
│                    0.010 │
│                    0.100 │
│                    1.000 │
│                   10.000 │
│                  100.000 │
│                 1000.000 │
│                10000.000 │
│               100000.000 │
│              1000000.000 │
│             10000000.000 │
│            100000000.000 │
│           1000000000.000 │
│          10000000000.000 │
│         100000000000.000 │
│        1000000000000.000 │
│       10000000000000.000 │
│      100000000000000.000 │
│     1000000000000000.000 │
│    10000000000000000.000 │
│   100000000000000000.000 │
│  1000000000000000000.000 │
│ -8446744073709551616.000 │
│  7766279631452241920.000 │
├──────────────────────────┤
│         24 rows          │
└──────────────────────────┘
```

Interestingly  when I insert those two overflowing values directly in duckdb, they ARE inserted correctly:
```bash
D insert into test(mycolumn) values (10000000000000000000.000), (100000000000000000000.000);
D select * from test;
┌───────────────────────────┐
│         mycolumn          │
│       decimal(24,3)       │
├───────────────────────────┤
│                     0.001 │
│                     0.010 │
│                     0.100 │
│                     1.000 │
│                    10.000 │
...
│     10000000000000000.000 │
│    100000000000000000.000 │
│   1000000000000000000.000 │
│  -8446744073709551616.000 │ <─┤ two largest values imported from postgres
│   7766279631452241920.000 │ <─┤
│  10000000000000000000.000 │     <─┤ two largest values inserted directly from duckdb repl 
│ 100000000000000000000.000 │     <─┤
├───────────────────────────┤
│          26 rows          │
└───────────────────────────┘
```

### OS:

Linux - Fedora 36

### PostgreSQL Version:

15.2

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Jan Hrček

### Affiliation:

Holmusk

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by theelderbeever** [comment]
In addition to this per the discussion I posted [here](https://github.com/duckdb/duckdb/discussions/8036)... If you define a table with a `NUMERIC(>38,_)` then the postgres_scanner fails to connect to the database altogether.

**Comment by tcboles** [comment]
I am seeing similar results when using the postgres scanner with numeric columns that have high precision. I put together a sample repo to reproduce the issue. https://github.com/tcboles/duckdb-postgres-scanner-bug

**Comment by Alex-Monahan** [comment]
I've also put together a Google Collab that installs postgres and the postgres scanner and can duplicate the issue (based on the great work by @tcboles above!)
https://colab.research.google.com/drive/1oC9THIM9H81eMgLEdnVvftipQnlkZB-N?usp=sharing

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed now in https://github.com/duckdb/postgres_scanner/pull/111.
