### ISSUE TITLE
Postgres_scanner does not detect the correct number of dimensions of an array in postgresql 

### ISSUE THREAD

**Issue by HackettJP** [duckdb/postgres_scanner#94]
### What happens?

if the array in postgresql in TEXT / float / VARCHAR that has two or more dimensions duckdb will either respond with either 

with '\0' on the first tuple response of the query , on the second  tuple will core dump / seg fault or go into unstable condition depending on the number of nested arrays.

### To Reproduce

any array within Postgresql with 2 or more dimensions will crash duckdb

### OS:

ubuntu 22.04

### PostgreSQL Version:

15.2   (Ubuntu 15.2-1.pgdg22.04+1)

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI on unix or C++ lib.

### Full Name:

James Hackett

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by HackettJP** [comment]
my work in progress of nested LIST Vectors ,

https://github.com/HackettJP/postgres_scanner_array/tree/HackettJP-Ndimension_WIP

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed now in https://github.com/duckdb/postgres_scanner/pull/111.
