### ISSUE TITLE
Meaning of "read into DuckDB tables"

### ISSUE THREAD

**Issue by rinormaloku** [duckdb/postgres_scanner#97]
### What happens?

In the sentence below the section in bold is not properly clarified:

>  The data can be queried directly from the underlying Postgres tables, or **read into DuckDB tables.**

How can that be done? Is it done automatically? Can I improve performance by reading Postgres data in DuckDB tables?

### To Reproduce

This might be the wrong location for this question, but I didn't know where to ask the question

### OS:

any

### PostgreSQL Version:

any

### DuckDB Version:

any

### DuckDB Client:

any

### Full Name:

Rinor Maloku

### Affiliation:

rinormaloku

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Hello!

This is not done automatically, but you can query from Postgres and insert into DuckDB. We have some details in this blog post: https://duckdb.org/2022/09/30/postgres-scanner.html#other-use-cases

Let me knownif you have further questions!

**Comment by Mytherin** [comment]
> I have one more question. When inserting data into DuckDB tables, are those automatically synchronized? (I would expect no, that would be some scary magic, but just verifying that it is not).

No, those would not be kept up to date. You either need to manually refresh, or keep querying the original tables.

Closing as the main issue/question has been answered.
